[package]
name = "rust-proxy"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aegisproxy-admin = { path = "../proxy-admin" }
aegisproxy-config = { path = "../proxy-config" }
aegisproxy-core = { path = "../proxy-core" }
aegisproxy-tls = { path = "../proxy-tls" }
clap = { version = "4", features = ["derive"] }
toml = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tokio-util = { version = "0.7", features = ["rt"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }

[dev-dependencies]
age = { version = "0.11.2", default-features = false }
rcgen = { version = "0.14", default-features = false, features = ["aws_lc_rs", "crypto", "pem"] }
