[package]
name = "aegisproxy-config"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aegisproxy-secrets = { path = "../proxy-secrets" }
ipnet = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
toml = "0.8"
url = { version = "2", features = ["serde"] }
